### ISSUE TITLE
Missing Header Files

### ISSUE THREAD

**Issue by NavSad** [0x0XDev/UserKernelAccess#1]
There are multiple missing header files, such as KernelTools.h, RuntimeSymPatch.h, and Types.h. The code will not work without these header files.

**Comment by ShatteredEggshells** [comment]
@NavSad did you find KernelTools.h and Types.h?

**Comment by EricRabil** [comment]
@NavSad did you find the missing headers?

**Comment by anonymouz4** [comment]
[RuntimeSymPatch](https://github.com/0x0XDev/RuntimeSymPatch) is a different Repo
Types.h just sets a couple typedef aliases for `uint64_t` so you can just replace them.

**Comment by EricRabil** [comment]
What about KernelTools.h? I can't find it anywhere online :(

**Comment by anonymouz4** [comment]
Well, everyone has there own Kernel Tools and mine are private and you don't really need them. All they are used for here are to write some bytes to memory via physical memory. There're 100 ways to do that, you can simple flip the `cr0` register to make the kernel memory writable. Sorry to say but if you can't fix that simple thing yourself, it's probably a really really bad idea to enable tfp0 in the first place
